[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudmesh-ai-example"
version = "0.1.0"
description = "example command for Cloudmesh AI"
readme = "README.md"
license = "Apache-2.0"
urls = { "Homepage" = "https://github.com/cloudmesh-ai/cloudmesh-ai-example" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: System Administrators",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "cloudmesh-ai-common",
]

[project.entry-points."cloudmesh.ai.cmc"]
"example" = "cloudmesh.ai.command.example.example_group"


[tool.cloudmesh-ai]
category = "foundation"
status = "stable"
order = 30
essential = true
readme = "A template to create a new command for Cloudmesh AI. This command is generated using the `cmc generate command` and serves as a starting point for developing new commands within the Cloudmesh AI ecosystem."
